### ISSUE TITLE
_delete_task_assignment() has code for locking db that does not work

### ISSUE THREAD

**Issue by cash** [hltcoe/turkle#119]
This is in views.py

Code:
```
    with transaction.atomic():
        # Lock access to the specified Task
        Task.objects.filter(id=task_id).select_for_update()

        task_assignment.delete()
```

The first query is never executed so there is no lock on that Task. I'm not sure I understand why it is there. It prevents anyone from accepting an assignment for that task, submitting an answer for that task, or returning that task while the delete operation of the task assignment is happening. Those all seem like safe operations between the query that creates the lock and the query that deletes the assignment.

**Comment by cash** [comment]
If user A submits a task assignment for task 1 at the same time as user B deletes a task assignment for that task, is it possible that we will record the task as being complete with fewer than the number of requested annotations?

**Comment by charman** [comment]
[views.py#L525](https://github.com/hltcoe/turkle/blob/2602da4b43b5af5bd2ddb7037b54ba5a78287fb1/turkle/views.py#L525) has a guard condition that only allows the TaskAssignment to be deleted if the TaskAssignment is incomplete:

```
    if task_assignment.completed:
        messages.error(request, u"The Task can't be returned because it has been completed")
        return redirect(index)
```

Deleting a TaskAssignment that has been created but not "completed" should not cause the Task status to be marked as complete with fewer than the number of requested annotations.

If there was a UI mechanism that allowed a *completed* TaskAssignment to be deleted (this could be done by directly manipulating the DB, but is not a workflow currently supported by the Turkle UI), then it would be possible for a Task to be marked as completed with fewer than the number of requested annotations.

**Comment by cash** [comment]
Deleting a user deletes task assignments. If a batch required 2 assignments per task, could the second assignment be submitted at the same time as an admin deletes a user and the task gets marked as complete before the delete query is issued? (I acknowledge that we are talking about a very rare possibility).

**Comment by charman** [comment]
When i said that deleting a completed TaskAssignment "is not a workflow currently supported by the Turkle UI," I had forgotten that the UI currently/still allows Users to be deleted - and deleting a User deletes all of their TaskAssignments.

Deleting a TaskAssignment (by, for example, deleting the associated User) does not currently update the `completed` flag for the associated Task. Turkle currently has logic to change `Task.completed` from `False` to `True`, but no logic to change `Task.completed` from `True` to `False` if/when TaskAssignments are deleted.

While this is definitely an issue (and should be an Issue), the topic of this Issue is the locking code wrapping [this call to `task_assignment.delete()` in `views.py`](https://github.com/hltcoe/turkle/blob/7bdf056af0fdec4e57847820be2737e93ec77556/turkle/views.py#L546):

```
    with transaction.atomic():
        # Lock access to the specified Task
        Task.objects.filter(id=task_id).select_for_update()

        task_assignment.delete()
```

I believe this can be safely changed to:

```
    task_assignment.delete()
```
