### ISSUE TITLE
Removing a group from a batch only works if restrict access is checked

### ISSUE THREAD

**Issue by cash** [hltcoe/turkle#142]
To reproduce:

1. Check restrict access
2. Select a group
3. Save and edit again
4. Remove all groups
5. Uncheck the restrict access
6. Save and edit again
7. Recheck the restrict access (and you'll see the previous group is still there)

Is this a bug? I at least did not expect it.

**Comment by charman** [comment]
> Is this a bug? I at least did not expect it.

I think this behavior is a (bad) design decision I made. The current [form processing code](https://github.com/hltcoe/turkle/blob/72a30cd4db87e6f9f0f24f5cb818b550ef8f5373/turkle/admin.py#L757) has a guard condition that only saves changes to group permissions if the "Restrict access" checkbox is checked.

I can change the behavior so that the group permissions are always saved, even if the form widgets for group permissions are hidden when the form is submitted.

**Comment by charman** [comment]
Thinking about this further, it's possible that this behavior is a partial hack to prevent our fragile command line scripts from breaking. The admin controller has a lot of convoluted workarounds for preserving the behavior of the current command line scripts that should be cleaned up once we have a proper REST API (#54).

**Comment by charman** [comment]
> Thinking about this further, it's possible that this behavior is a partial hack to prevent our fragile command line scripts from breaking. The admin controller has a lot of convoluted workarounds for preserving the behavior of the current command line scripts that should be cleaned up once we have a proper REST API (#54).

Changing the behavior does not break the current test suite for the command line scripts. `scripts/upload_tasks.py` supports a "login required" flag, but do not provide a mechanism for restricting Batch access to specific groups and/or users.
