### ISSUE TITLE
Submit button in form not detected properly

### ISSUE THREAD

**Issue by Genius1237** [hltcoe/turkle#151]
The template I'm using has a submit button of the form `<button type="submit" onclick="submitClicked(event)">Submit</button>`. Turkle fails to detect this and adds in an extra submit button in the UI. The above button is detected normally by MTurk.

I believe that the faulty piece of code is [this](https://github.com/hltcoe/turkle/blob/3eb2fec9eb0f9903ce8983ff51208a99071a33dc/turkle/models.py#L798). It's looking for objects of type input and not button. Changing this/Adding in a filter for button `bool(soup.select('button[type=submit]'))` might fix it.

**Comment by cash** [comment]
Thanks for the report. @charman Any thoughts on this? Seems like checking for both input and button should work.

**Comment by cash** [comment]
@Genius1237 I'm unable to reproduce this on MTurk.

Here is my template:
```
<p>This is a test</p>

<p><input type="text" name="field1"></p>

<button type="submit" onclick="submitClicked(event)">Submit</button>
```

And here is what MTurk renders:
![image](https://user-images.githubusercontent.com/199558/152337821-ceeef3e4-f815-429a-a106-7594549d5a2f.png)

MTurk adds the submit button because it doesn't detect the `<button>` tag as submitting the form. I tried playing around with different combinations of `<button>` fields to see if I could get MTurk to detect it but was unable. If you could post a minimal template that works with MTurk but not with Turkle, that would be great.

**Comment by Genius1237** [comment]
Hey. I was originally using a template that used the MTurk custom <crowd-form> element. This element wasn't working directly on Turkle, so I made some changes to my template to get it working. It looks like I did not test out this modified template on Mturk. i just assumed that it would work, but I guess it does not. 

I'm sorry for the confusion, but it looks like this might not actually be an issue. I will try to test it during the weekend and confirm that.
