### ISSUE TITLE
Adding a new user via script does not work

### ISSUE THREAD

**Issue by bricksdont** [hltcoe/turkle#35]
Adding a new user via the script

https://github.com/hltcoe/turkle/blob/master/scripts/add_user.py

does not work for us, even though the script says "Success" at the end.

```
$ python add_user.py -u bricksdont user-test-from-script password-test-from-script --server [server name]
Admin password:
Success
```

After that, the users overview in the GUI does not show this new user.

The exact same happens with `import_users.py`. We also tried logging into the machine the server is running on, then running the script with `localhost`.

What could be potential reasons for this?

**Comment by cash** [comment]
@bricksdont We found a bug where the script does not check for invalid user names. Could you try manually creating that user and see if it gets rejected?

**Comment by bricksdont** [comment]
Thanks for your answer!

Adding this user (`user-test-from-script`) in the GUI works fine.

**Comment by cash** [comment]
I don't know of any password character limitations. I will add additional error checking to the script today and we'll see if it catches a validation issue.

**Comment by cash** [comment]
@bricksdont I believe I have identified and fixed the problem. The fix is in master. You don't have to change anything running on the server to test. Just clone the repo to your laptop and run the script. The scripts require 2 python dependencies: requests and BeautifulSoup. These get installed when running pip install -r requirements.txt when setting up turkle or you can manually install them in a virtual environment or you may have already installed them in your python distribution.

**Comment by bricksdont** [comment]
Thanks! Works perfectly now, but some details are trial and error for me:
- server address only worked if I explicitly use "https://"
- I expected that I should use "server_address:port", but only "server_adress" without the port worked

Still, this issue can be closed.

> You don't have to change anything running on the server to test.
My comment about updating local code was about a different issue, where the change is not in the `scripts` folder.

**Comment by bricksdont** [comment]
Just saw that your commits already include some more documentation about URLs and protocols, closing.
